console.log(typeof(1))
console.log(typeof(1.1))
console.log(typeof("1.1"))
console.log(typeof(true))
console.log(typeof(null))
console.log(typeof(undefined))
console.log(typeof([]))
console.log(typeof({}))
